<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DataSortingGame.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Defaults\*.json" LogicalName="Defaults.%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
